<a href="https://colab.research.google.com/github/Nathianny/Projetos_LP/blob/main/projeto_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df = pd.read_excel(r'/content/drive/MyDrive/Colab Notebooks/projeto-01/vendas (1).xlsx')
display(df)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,22,2021-11-12,Roma/PB,Sapato Estampa,1,358,358
1,51,2023-02-06,Roma/PB,Camiseta,2,180,360
2,33,2022-08-14,Serraria/PB,Sapato Xadrez,1,368,368
3,77,2022-11-13,Arara/PB,Relógio,3,200,600
4,71,2021-04-22,Serraria/PB,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
100995,64,2021-09-14,Serraria/PB,Mochila,4,270,1080
100996,48,2021-09-26,Araçagí/PB,Pulseira Estampa,1,87,87
100997,80,2022-03-05,Belém/PB,Camisa Listrado,1,108,108
100998,55,2022-01-11,Guarabira/PB,Short Linho,2,133,266
100999,39,2023-04-13,Bananeiras/PB,Calça,5,154,770

In [2]:
faturamento = df[['ID Loja', 'Valor Final']].groupby('ID Loja').sum()

In [3]:
faturamento = faturamento.sort_values(by='Valor Final', ascending=False)

In [4]:
faturamento = df[['ID Loja', 'Valor Final']].groupby('ID Loja').sum()
faturamento = faturamento.sort_values(by='Valor Final', ascending=False)
display(faturamento)

                      Valor Final
ID Loja
Roma/PB                   3909652
Arara/PB                  3904270
Serraria/PB               3830794
Solânea/PB                3823439
Araçagí/PB                3808472
Guarabira/PB              3806257
Borborema/PB              3791848
Bananeiras/PB             3779202
Caiçara/PB                3765510
Belém/PB                  3747835
Cacimba de Dentro/PB      3710554

In [5]:
quantidade = df[['ID Loja', 'Quantidade']].groupby('ID Loja').sum()
quantidade = quantidade.sort_values(by='ID Loja', ascending=False)
display(quantidade)

                      Quantidade
ID Loja
Solânea/PB                 20126
Serraria/PB                20061
Roma/PB                    20297
Guarabira/PB               20010
Caiçara/PB                 19678
Cacimba de Dentro/PB       19454
Borborema/PB               19702
Belém/PB                   19411
Bananeiras/PB              19759
Araçagí/PB                 19922
Arara/PB                   20273

In [6]:
import pandas as pd
cores_primarias = pd.Series(['Amarelo', 'Vermelho', 'Azul'])
turmas = pd.Series(['Turma 01', 42, True, 'Turma 02', 39, True])

In [7]:
print(turmas[3])

Turma 02

In [8]:
ticket_medio = (faturamento['Valor Final'] / quantidade['Quantidade']).to_frame()

In [9]:
display(ticket_medio)

                               0
ID Loja
Arara/PB              192.584719
Araçagí/PB            191.169160
Bananeiras/PB         191.264841
Belém/PB              193.077894
Borborema/PB          192.460055
Cacimba de Dentro/PB  190.734759
Caiçara/PB            191.356337
Guarabira/PB          190.217741
Roma/PB               192.622161
Serraria/PB           190.957280
Solânea/PB            189.975107

In [10]:
ticket_medio = ticket_medio.rename(columns={0: 'Ticket Medio'})

In [11]:
ticket_medio = ticket_medio.sort_values(by= 'Ticket Medio', ascending=False)

In [12]:
display(ticket_medio)

                      Ticket Medio
ID Loja
Belém/PB                193.077894
Roma/PB                 192.622161
Arara/PB                192.584719
Borborema/PB            192.460055
Caiçara/PB              191.356337
Bananeiras/PB           191.264841
Araçagí/PB              191.169160
Serraria/PB             190.957280
Cacimba de Dentro/PB    190.734759
Guarabira/PB            190.217741
Solânea/PB              189.975107

In [14]:
# importação das bibliotecas
import smtplib 
import email.message

# método eviar_email
def enviar_email(loja, resumo_loja):
  # criando o conteúdo da menssagem
  corpo_email = f'''
  <p style="text-align: justfy;">Caríssimos ao tempo que lhe cumprimentamos cordialmente,enviamos o relatório gerencial da loja sob sua responabilidade</p>
  {resumo_loja.to_html()}
  <p style="text-align: justfy;">Sem mais para o momento, nos despedimos e nos colocamos a sua inteira disposição para quaisquer esclarecimentos.</p>
  <p style="text-align: justfy;">Atenciosamente, equipe de sistemas.</p>
  '''

  # criando o email
  msg = email.message.Message()
  msg['Sunject'] = f'Relatório Gerencial - {loja}'
  # conta que será usada para o envio
  msg['From'] = 'remetentte@gmail.com'
  # senha da conta que será usada para o envio
  password = 'senha'
  # conta para o qual o email será enviado (não precisa ser gmail.com)
  msg['To'] = 'destinatario@gmail.com'
  msg.add_header('Content-Type, text/html')
  msg.set_payload(corpo_email)

  # estabelecendo uma conexão com Servidor SMTP
  server = smtplib.SMTP('smtp.gmail.com:587')

  # iniciando uma conexão segura TLS (Transport Layer Security) com Servidor SMTP
  server.starttls()

  # passagem de credenciais para enviar o e-mail
  server.login(msg['From'], password)
  # envio da mensagem
  server.sendmail(msg['From'], [msg['To']], msg.as_string().encode('utf-8'))

  print('E-mail enviado')

In [34]:
loja = 'Bananeiras/PB'
# Filtrando os dados para uma filial definida pela loja
df_filial = df.loc[df['ID Loja'] == loja, ['ID Loja', 'Quantidade', 'Valor Final']]

# Agrupando e cauculando o somatório dos registros
relatorio_filial = df_filial.groupby('ID Loja').sum()

# Cauculando o valor médio das vendas do periodo
relatorio_filial['Ticket Médio'] = relatorio_filial['Valor Final']/relatorio_filial['Quantidade']

display(relatorio_filial)

               Quantidade  Valor Final  Ticket Médio
ID Loja
Bananeiras/PB       19759      3779202    191.264841

In [41]:
# criando a lista de filiais
lojas = df['ID Loja'].unique()

for loja in lojas:
  # Filtrando os dados para uma filial definida pela loja
  df_filial = df.loc[df['ID Loja'] == loja, ['ID Loja', 'Quantidade', 'Valor Final']]

  # Agrupando e cauculando o somatório dos registros
  relatorio_filial = df_filial.groupby('ID Loja').sum()

  # Cauculando o valor médio das vendas do periodo
  relatorio_filial['Ticket Médio'] = relatorio_filial['Valor Final']/relatorio_filial['Quantidade']

  display(relatorio_filial)

         Quantidade  Valor Final  Ticket Médio
ID Loja
Roma/PB       20297      3909652    192.622161

             Quantidade  Valor Final  Ticket Médio
ID Loja
Serraria/PB       20061      3830794     190.95728

          Quantidade  Valor Final  Ticket Médio
ID Loja
Arara/PB       20273      3904270    192.584719

               Quantidade  Valor Final  Ticket Médio
ID Loja
Bananeiras/PB       19759      3779202    191.264841

            Quantidade  Valor Final  Ticket Médio
ID Loja
Araçagí/PB       19922      3808472     191.16916

            Quantidade  Valor Final  Ticket Médio
ID Loja
Caiçara/PB       19678      3765510    191.356337

              Quantidade  Valor Final  Ticket Médio
ID Loja
Guarabira/PB       20010      3806257    190.217741

                      Quantidade  Valor Final  Ticket Médio
ID Loja
Cacimba de Dentro/PB       19454      3710554    190.734759

              Quantidade  Valor Final  Ticket Médio
ID Loja
Borborema/PB       19702      3791848    192.460055

            Quantidade  Valor Final  Ticket Médio
ID Loja
Solânea/PB       20126      3823439    189.975107

          Quantidade  Valor Final  Ticket Médio
ID Loja
Belém/PB       19411      3747835    193.077894